CREATE TABLE IF NOT EXISTS setores_membros (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  setor_id INT UNSIGNED NOT NULL,
  email VARCHAR(255) NOT NULL,
  nome VARCHAR(80) NOT NULL
) ENGINE = InnoDB;
