CREATE TABLE IF NOT EXISTS nc_cadastro (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  data_criado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  franquia_id INT UNSIGNED NOT NULL,
  setor_id INT UNSIGNED NOT NULL,
  motivo_id INT UNSIGNED NOT NULL,
  submotivo_id INT UNSIGNED NOT NULL,
  condominio VARCHAR(255),
  responsavel_id INT UNSIGNED NOT NULL,
  responsavel VARCHAR(80) NOT NULL,
  observacoes TEXT(1000) NOT NULL
) ENGINE = InnoDB;
